# โครงสร้างการควบคุม (Control Structures) ในภาษา Python
## สำหรับนักศึกษาภูมิศาสตร์

---

### 🎯 วัตถุประสงค์การเรียนรู้
หลังจากเรียนจบบทนี้ นักศึกษาจะสามารถ:
1. ใช้คำสั่งเงื่อนไข (if-elif-else) ในการตัดสินใจ
2. ใช้คำสั่งวนซ้ำ (for loop, while loop) ในการประมวลผลข้อมูล
3. ควบคุมการทำงานของ loop ด้วย break และ continue
4. เข้าใจและใช้งาน nested loops
5. ประยุกต์ใช้กับข้อมูลภูมิศาสตร์จริง

### 📚 เนื้อหาที่จะเรียน
1. คำสั่งเงื่อนไข (Conditional Statements)
2. คำสั่งวนซ้ำ for loop
3. คำสั่งวนซ้ำ while loop
4. การควบคุม loop (break, continue)
5. Nested loops
6. Mini Project: ระบบวิเคราะห์คุณภาพอากาศ

---

## 📊 ข้อมูลตัวอย่างที่ใช้ในบทเรียน

เราจะใช้ข้อมูลภูมิศาสตร์ง่ายๆ ต่อไปนี้:

In [ ]:
# ข้อมูลอุณหภูมิ 8 วัน (องศาเซลเซียส)
temperatures = [28, 32, 35, 27, 30, 33, 29, 31]

# ข้อมูลปริมาณฝน 8 วัน (มิลลิเมตร)
rainfall = [0, 5, 12, 0, 0, 25, 8, 0]

# ข้อมูล PM2.5 8 วัน (ไมโครกรัม/ลูกบาศก์เมตร)
pm25 = [45, 78, 120, 55, 89, 150, 62, 41]

# รายชื่อจังหวัด
locations = ['กรุงเทพ', 'เชียงใหม่', 'ขอนแก่น', 'ภูเก็ต', 'อุดรธานี']

print("✅ เตรียมข้อมูลเรียบร้อยแล้ว!")

✅ เตรียมข้อมูลเรียบร้อยแล้ว!


---
# ส่วนที่ 1: คำสั่งเงื่อนไข (Conditional Statements)

คำสั่งเงื่อนไขช่วยให้โปรแกรมสามารถตัดสินใจได้ตามเงื่อนไขที่กำหนด

## 1.1 คำสั่ง if พื้นฐาน

In [ ]:
# ตัวอย่าง: ตรวจสอบว่าอุณหภูมิสูงเกิน 35 องศาหรือไม่
temp = 40

if temp > 35:
    print(f"🌡️ อุณหภูมิ {temp}°C สูงมาก! ระวังลมแดด")

🌡️ อุณหภูมิ 40°C สูงมาก! ระวังลมแดด


## 1.2 คำสั่ง if-else

In [ ]:
# ตัวอย่าง: ตรวจสอบว่าวันนั้นฝนตกหรือไม่
rain = 25

if rain > 0:
    print(f"🌧️ วันนี้ฝนตก {rain} mm")
else:
    print("☀️ วันนี้ไม่มีฝน")

🌧️ วันนี้ฝนตก 25 mm


## 1.3 คำสั่ง if-elif-else

In [ ]:
# ตัวอย่าง: จำแนกระดับ PM2.5
pm = 130

if pm <= 50:
    print(f"PM2.5 = {pm} → 🟢 คุณภาพอากาศดี")
elif pm <= 100:
    print(f"PM2.5 = {pm} → 🟡 คุณภาพอากาศปานกลาง")
elif pm <= 120:
    print(f"PM2.5 = {pm} → 🟠 คุณภาพอากาศแย่ กึ่งยิงกึ่งผ่าน")
elif pm <= 150:
    print(f"PM2.5 = {pm} → 🟠 คุณภาพอากาศแย่")
else:
    print(f"PM2.5 = {pm} → 🔴 คุณภาพอากาศอันตราย!")

PM2.5 = 130 → 🟠 คุณภาพอากาศแย่


---
## 📝 แบบฝึกหัดที่ 1: จำแนกประเภทพืชพรรณจากค่า NDVI

**คำอธิบาย:** NDVI (Normalized Difference Vegetation Index) เป็นค่าที่ใช้บอกความหนาแน่นของพืชพรรณ

**เกณฑ์:**
- NDVI < 0.2 → พื้นที่เปลือย/น้ำ
- 0.2 ≤ NDVI < 0.4 → พืชพรรณน้อย
- 0.4 ≤ NDVI < 0.6 → พืชพรรณปานกลาง
- NDVI ≥ 0.6 → ป่าไม้/พืชพรรณหนาแน่น

**ให้เขียนโปรแกรม** รับค่า NDVI และแสดงประเภทพืชพรรณ

In [ ]:
# แบบฝึกหัดที่ 1: เขียนโค้ดของคุณที่นี่
ndvi = 0.45  # ทดลองเปลี่ยนค่านี้

# เขียนโค้ดตรงนี้
if ndvi < 0.2:
    print(f"NDVI = {ndvi} → พื้นที่เปลือย/น้ำ")
elif ndvi <= 0.4:
    print(f"NDVI = {ndvi} → พืชพรรณน้อย")
elif ndvi <= 0.6:
    print(f"NDVI = {ndvi} → พืชพรรณปานกลาง")
elif ndvi:
    print(f"NDVI = {ndvi} → ป่าไม้/พืชพรรณหนาแน่น")

NDVI = 0.45 → พืชพรรณปานกลาง


---
## 📝 แบบฝึกหัดที่ 2: ตรวจสอบพิกัดว่าอยู่ในประเทศไทยหรือไม่

**คำอธิบาย:** ประเทศไทยมี latitude ประมาณ 5.6°N ถึง 20.5°N

**ให้เขียนโปรแกรม** รับค่า latitude และตรวจสอบว่าอยู่ในประเทศไทยหรือไม่

In [ ]:
# แบบฝึกหัดที่ 2: เขียนโค้ดของคุณที่นี่
latitude = 13.75 # ทดลองเปลี่ยนค่านี้

# เขียนโค้ดตรงนี้
latitude = 17

if latitude >= 5.6 and latitude <= 20.5:
    print(f"อยู่ในประเทศไทย {latitude} องศาเหนือ")
else:
    print("ไม่อยู่ในประเทศไทย")


อยู่ในประเทศไทย 17 องศาเหนือ


---
# ส่วนที่ 2: คำสั่งวนซ้ำ for loop

for loop ใช้สำหรับวนซ้ำผ่านข้อมูลใน list, tuple, string หรือ range

## 2.1 วนซ้ำใน list

In [ ]:
# ตัวอย่าง: แสดงอุณหภูมิทั้ง 8 วัน
print ("อุณหภูมิรายวัน:")
for temp in temperatures :
    print(f"  🌡️ {temp} °C")

อุณหภูมิรายวัน:
  🌡️ 28 °C
  🌡️ 32 °C
  🌡️ 35 °C
  🌡️ 27 °C
  🌡️ 30 °C
  🌡️ 33 °C
  🌡️ 29 °C
  🌡️ 31 °C


## 2.2 คำนวณค่าเฉลี่ย

In [ ]:
# ตัวอย่าง: คำนวณค่าเฉลี่ยอุณหภูมิ
total = 0
count = 0

for temp in temperatures:
    total += temp
    count += 1

average = total / count
print(f"อุณหภูมิเฉลี่ย: {average:.2f}°C")

อุณหภูมิเฉลี่ย: 30.62°C


## 2.3 วนซ้ำด้วย range()

In [ ]:
# ตัวอย่าง: แสดงวันที่ 1-10
print("วันที่ในเดือน:")
for day in range(1, 11):  # 1-10
    print(f"  วันที่ {day}")

วันที่ในเดือน:
  วันที่ 1
  วันที่ 2
  วันที่ 3
  วันที่ 4
  วันที่ 5
  วันที่ 6
  วันที่ 7
  วันที่ 8
  วันที่ 9
  วันที่ 10


## 2.4 วนซ้ำพร้อมเงื่อนไข

In [ ]:
# ตัวอย่าง: นับจำนวนวันที่ฝนตก
rainy_days = 0

for rain in rainfall:
    if rain > 0:
        rainy_days += 1

print(f"จำนวนวันที่ฝนตก: {rainy_days} วัน")

จำนวนวันที่ฝนตก: 4 วัน


In [ ]:
# ตัวอย่าง: หาวันที่อุณหภูมิสูงที่สุด
max_temp = temperatures[0]
max_day = 1

for i in range(len(temperatures)):
    if temperatures[i] > max_temp:
        max_temp = temperatures[i]
        max_day = i + 1

print(f"วันที่ {max_day} มีอุณหภูมิสูงที่สุด {max_temp}°C")

วันที่ 3 มีอุณหภูมิสูงที่สุด 35°C


## 2.5 ใช้ enumerate() - แสดงทั้งลำดับและค่า

In [ ]:
# ตัวอย่าง: แสดงวันและอุณหภูมิพร้อมกัน
print("อุณหภูมิรายวัน:")
for day, temp in enumerate(temperatures, start=1):
    print(f"  วันที่ {day}: {temp}°C")

อุณหภูมิรายวัน:
  วันที่ 1: 28°C
  วันที่ 2: 32°C
  วันที่ 3: 35°C
  วันที่ 4: 27°C
  วันที่ 5: 30°C
  วันที่ 6: 33°C
  วันที่ 7: 29°C
  วันที่ 8: 31°C


---
## 📝 แบบฝึกหัดที่ 3: คำนวณค่าเฉลี่ย PM2.5

**ให้เขียนโปรแกรม** วนลูปคำนวณค่าเฉลี่ย PM2.5 ทั้ง 8 วัน และแสดงผล

In [ ]:
# แบบฝึกหัดที่ 3: เขียนโค้ดของคุณที่นี่

# เขียนโค้ดตรงนี้
total = 0
count = 0

for pm_value in pm25:
    total += pm_value
    count += 1

average = total / count
print(f"ค่าเฉลี่ย PM2.5: {average:.2f}")

ค่าเฉลี่ย PM2.5: 80.00


---
## 📝 แบบฝึกหัดที่ 4: นับจำนวนวันที่อากาศแย่

**ให้เขียนโปรแกรม** นับว่ามีกี่วันที่ PM2.5 เกิน 100 (คุณภาพอากาศแย่)

In [ ]:
# แบบฝึกหัดที่ 4: เขียนโค้ดของคุณที่นี่
pm25 = [45, 78, 120, 55, 89, 150, 62, 41]
# เขียนโค้ดตรงนี้
bad_air_days = 0

for value in pm25:
    if value > 100:
        bad_air_days += 1

print(f"จำนวนวันที่ PM2.5 เกิน 100 : {bad_air_days} วัน")

จำนวนวันที่ PM2.5 เกิน 100 : 2 วัน


---
## 📝 แบบฝึกหัดที่ 5: แสดงชื่อจังหวัดพร้อมเลขลำดับ

**ให้เขียนโปรแกรม** ใช้ enumerate() แสดงชื่อจังหวัดทั้งหมดพร้อมเลขลำดับ

ผลลัพธ์ที่ต้องการ:
```
1. กรุงเทพ
2. เชียงใหม่
...
```

In [ ]:
# แบบฝึกหัดที่ 5: เขียนโค้ดของคุณที่นี่

# เขียนโค้ดตรงนี้
print("จังหวัด:")
for day, location_name in enumerate(locations, start=1):
    print(f"จังหวัด {day}. {location_name}")

จังหวัด:
จังหวัด 1. กรุงเทพ
จังหวัด 2. เชียงใหม่
จังหวัด 3. ขอนแก่น
จังหวัด 4. ภูเก็ต
จังหวัด 5. อุดรธานี


---
# ส่วนที่ 3: คำสั่งวนซ้ำ while loop

while loop จะวนซ้ำไปเรื่อยๆ ตราบใดที่เงื่อนไขยังเป็นจริง

## 3.1 ตัวอย่างพื้นฐาน

In [ ]:
# ตัวอย่าง: นับจำนวนวันจนครบ 10 วัน
day = 1

while day <= 10:
    print(f"วันที่ {day}")
    day += 1  # เพิ่มค่า day

print("ครบ 10 วันแล้ว!")

วันที่ 1
วันที่ 2
วันที่ 3
วันที่ 4
วันที่ 5
วันที่ 6
วันที่ 7
วันที่ 8
วันที่ 9
วันที่ 10
ครบ 10 วันแล้ว!


## 3.2 while loop กับเงื่อนไข

In [ ]:
# ตัวอย่าง: จำลองการอ่านอุณหภูมิจนกว่าจะเกิน 35 องศา
temps_sample = [28, 30, 32, 34, 36, 38]
i = 0

while i < len(temps_sample) and temps_sample[i] <= 35:
    print(f"วันที่ {i+1}: อุณหภูมิ {temps_sample[i]}°C - ปกติ")
    i += 1

if i < len(temps_sample):
    print(f"⚠️ วันที่ {i+1}: อุณหภูมิ {temps_sample[i]}°C - สูงเกินเกณฑ์!")

วันที่ 1: อุณหภูมิ 28°C - ปกติ
วันที่ 2: อุณหภูมิ 30°C - ปกติ
วันที่ 3: อุณหภูมิ 32°C - ปกติ
วันที่ 4: อุณหภูมิ 34°C - ปกติ
⚠️ วันที่ 5: อุณหภูมิ 36°C - สูงเกินเกณฑ์!


## 3.3 ความแตกต่าง for vs while

**ใช้ for loop เมื่อ:**
- รู้จำนวนรอบที่ต้องวนแน่นอน
- ต้องการวนซ้ำผ่านข้อมูลใน list, dictionary

**ใช้ while loop เมื่อ:**
- ไม่รู้จำนวนรอบที่แน่นอน
- ต้องการวนซ้ำจนกว่าเงื่อนไขจะเป็นเท็จ
- สร้าง menu หรือ interactive program

---
## 📝 แบบฝึกหัดที่ 6: การเพิ่มพื้นที่ป่าไม้

**โจทย์:** เริ่มต้นมีพื้นที่ป่า 5,000 ไร่ และเพิ่มขึ้นปีละ 500 ไร่

**ให้เขียนโปรแกรม** ใช้ while loop นับว่าต้องใช้เวลากี่ปีจึงจะมีพื้นที่ป่า 10,000 ไร่

In [ ]:
# แบบฝึกหัดที่ 6: เขียนโค้ดของคุณที่นี่
forest_area = 5000  # ไร่
target = 10000      # ไร่
years = 0

# เขียนโค้ดตรงนี้
while forest_area < target:
    forest_area += 500
    years += 1

print(f"ต้องใช้เวลา {years} ปี ในการเพิ่มพื้นที่ป่าให้ได้ {target} ไร่")

ต้องใช้เวลา 10 ปี ในการเพิ่มพื้นที่ป่าให้ได้ 10000 ไร่


---
# ส่วนที่ 4: การควบคุม Loop (break และ continue)

- **break**: หยุด loop ทันที
- **continue**: ข้ามรอบนี้ไปรอบถัดไป

## 4.1 break - หยุด loop ทันที

In [ ]:
# ตัวอย่าง: หยุดทันทีที่พบ PM2.5 เกิน 150 (อันตราย)
print("ตรวจสอบคุณภาพอากาศ:")
for day, pm in enumerate(pm25, start=1):
    if pm > 150:
        print(f"🔴 วันที่ {day}: PM2.5 = {pm} - อันตราย! หยุดการตรวจสอบ")
        break
    else:
        print(f"วันที่ {day}: PM2.5 = {pm}")

ตรวจสอบคุณภาพอากาศ:
วันที่ 1: PM2.5 = 45
วันที่ 2: PM2.5 = 78
วันที่ 3: PM2.5 = 120
วันที่ 4: PM2.5 = 55
วันที่ 5: PM2.5 = 89
วันที่ 6: PM2.5 = 150
วันที่ 7: PM2.5 = 62
วันที่ 8: PM2.5 = 41


## 4.2 continue - ข้ามรอบนี้

In [ ]:
# ตัวอย่าง: แสดงเฉพาะวันที่มีฝนตก (ข้ามวันที่ไม่มีฝน)
print("วันที่ฝนตก:")
for day, rain in enumerate(rainfall, start=1):
    if rain == 0:
        continue  # ข้ามวันที่ไม่มีฝน
    print(f"  🌧️ วันที่ {day}: ฝน {rain} mm")

วันที่ฝนตก:
  🌧️ วันที่ 2: ฝน 5 mm
  🌧️ วันที่ 3: ฝน 12 mm
  🌧️ วันที่ 6: ฝน 25 mm
  🌧️ วันที่ 7: ฝน 8 mm


---
## 📝 แบบฝึกหัดที่ 7: ข้าม Missing Data

**โจทย์:** ข้อมูลอุณหภูมิบางวันอาจมีค่า -999 (แทน missing data)

**ให้เขียนโปรแกรม** วนลูปแสดงอุณหภูมิ แต่ข้ามวันที่มีค่า -999

```python
temps_with_missing = [28, -999, 32, 35, -999, 30, 33]
```

In [ ]:
# แบบฝึกหัดที่ 7: เขียนโค้ดของคุณที่นี่
temps_with_missing = [28, -999, 32, 35, -999, 30, 33]

# เขียนโค้ดตรงนี้
print("อุณหภูมิ:")
for day, current_temp in enumerate(temps_with_missing, start=1):
    if current_temp == -999:
        continue  # ข้ามวันที่มีค่า -999
    print(f"  {day}: อุณหภูมิ {current_temp} องศา")

อุณหภูมิ:
  1: อุณหภูมิ 28 องศา
  3: อุณหภูมิ 32 องศา
  4: อุณหภูมิ 35 องศา
  6: อุณหภูมิ 30 องศา
  7: อุณหภูมิ 33 องศา


---
## 📝 แบบฝึกหัดที่ 8: หยุดเมื่อพบค่าอันตราย

**โจทย์:** ตรวจสอบข้อมูล PM2.5 และหยุดทันทีที่พบค่าเกิน 150

**ให้เขียนโปรแกรม** วนลูปตรวจสอบ PM2.5 และ break เมื่อพบค่าอันตราย

```python
pm_data = [45, 60, 85, 95, 155, 70, 80]
```

In [ ]:
# แบบฝึกหัดที่ 8: เขียนโค้ดของคุณที่นี่
pm_data = [45, 60, 85, 95, 155, 70, 80]

# เขียนโค้ดตรงนี้
print("ตรวจสอบข้อมูล PM2.5:")
for day, current_pm in enumerate(pm_data, start=1):
    if current_pm > 150:
        print(f"🔴 วันที่ {day}: PM2.5 = {current_pm} - อันตราย! หยุดการตรวจสอบ")
        break
    else:
        print(f"วันที่ {day}: PM2.5 = {current_pm}")

ตรวจสอบข้อมูล PM2.5:
วันที่ 1: PM2.5 = 45
วันที่ 2: PM2.5 = 60
วันที่ 3: PM2.5 = 85
วันที่ 4: PM2.5 = 95
🔴 วันที่ 5: PM2.5 = 155 - อันตราย! หยุดการตรวจสอบ


---
# ส่วนที่ 5: Nested Loops (Loop ซ้อน Loop)

Loop ซ้อนกันใช้สำหรับข้อมูลที่มีหลายมิติ เช่น ตาราง, grid

## 5.1 ตัวอย่างง่ายๆ

In [ ]:
# ตัวอย่าง: แสดงตารางอุณหภูมิ 3 เมือง x 5 วัน
cities = ['กรุงเทพ', 'เชียงใหม่', 'ภูเก็ต']
temps_by_city = [
    [32, 33, 31, 34, 32],  # กรุงเทพ
    [28, 29, 27, 30, 28],  # เชียงใหม่
    [30, 31, 30, 32, 31]   # ภูเก็ต
]

print("อุณหภูมิรายเมือง:")
for i in range(len(cities)):
    print(f"\n{cities[i]}:")
    for day in range(len(temps_by_city[i])):
        print(f"  วันที่ {day+1}: {temps_by_city[i][day]}°C")

อุณหภูมิรายเมือง:

กรุงเทพ:
  วันที่ 1: 32°C
  วันที่ 2: 33°C
  วันที่ 3: 31°C
  วันที่ 4: 34°C
  วันที่ 5: 32°C

เชียงใหม่:
  วันที่ 1: 28°C
  วันที่ 2: 29°C
  วันที่ 3: 27°C
  วันที่ 4: 30°C
  วันที่ 5: 28°C

ภูเก็ต:
  วันที่ 1: 30°C
  วันที่ 2: 31°C
  วันที่ 3: 30°C
  วันที่ 4: 32°C
  วันที่ 5: 31°C


## 5.2 ประยุกต์ใช้กับ Grid

In [ ]:
# ตัวอย่าง: วิเคราะห์ข้อมูล grid 3x3 (เหมือน raster)
grid = [
    [45, 52, 48],
    [55, 120, 60],  # ค่ากลางสูงมาก!
    [50, 58, 53]
]

print("PM2.5 Grid (3x3):")
max_value = 0
max_row = 0
max_col = 0

for row in range(3):
    for col in range(3):
        value = grid[row][col]
        print(f"  [{row},{col}] = {value}", end="  ")

        # หาค่าสูงสุด
        if value > max_value:
            max_value = value
            max_row = row
            max_col = col
    print()  # ขึ้นบรรทัดใหม่

print(f"\nค่าสูงสุด: {max_value} ที่ตำแหน่ง [{max_row},{max_col}]")

PM2.5 Grid (3x3):
  [0,0] = 45    [0,1] = 52    [0,2] = 48  
  [1,0] = 55    [1,1] = 120    [1,2] = 60  
  [2,0] = 50    [2,1] = 58    [2,2] = 53  

ค่าสูงสุด: 120 ที่ตำแหน่ง [1,1]


---
## 📝 แบบฝึกหัดที่ 9: วิเคราะห์ PM2.5 หลายเมือง

**โจทย์:** มีข้อมูล PM2.5 ของ 3 เมือง 7 วัน

**ให้เขียนโปรแกรม:**
1. แสดงข้อมูล PM2.5 ทุกเมืองทุกวัน
2. คำนวณค่าเฉลี่ย PM2.5 ของแต่ละเมือง
3. หาเมืองที่มีค่าเฉลี่ยสูงที่สุด

```python
cities = ['กรุงเทพ', 'เชียงใหม่', 'ขอนแก่น']
pm_by_city = [
    [45, 50, 55, 48, 52, 60, 58],  # กรุงเทพ
    [85, 90, 120, 95, 100, 88, 92], # เชียงใหม่
    [55, 60, 65, 58, 62, 70, 68]   # ขอนแก่น
]
```

In [ ]:
# แบบฝึกหัดที่ 9: เขียนโค้ดของคุณที่นี่
cities = ['กรุงเทพ', 'เชียงใหม่', 'ขอนแก่น']
pm_by_city = [
    [45, 50, 55, 48, 52, 60, 58], # กรุงเทพ
    [85, 90, 120, 95, 100, 88, 92], # เชียงใหม่
    [55, 60, 65, 58, 62, 70, 68] # ขอนแก่น
]

# เขียนโค้ดตรงนี้
def classify_pm25(pm_value):
    if pm_value <= 50:
        return f"{pm_value} 🟢 ดี"
    elif 51 <= pm_value <= 100:
        return f"{pm_value} 🟡 ปานกลาง"
    elif 101 <= pm_value <= 150:
        return f"{pm_value} 🟠 แย่"
    else:
        return f"{pm_value} 🔴 อันตราย!"

print("=== วิเคราะห์คุณภาพอากาศ 3 จังหวัด ===")

average_pm_by_city = []
worst_city_avg = -1
worst_city_name = ""

for i, city in enumerate(cities):
    print(f"\n{city}:")
    city_pm_values = pm_by_city[i]
    city_total_pm = 0

    for day_idx, pm_value in enumerate(city_pm_values):
        classification = classify_pm25(pm_value)
        print(f"  วันที่ {day_idx+1}: PM2.5 = {classification}")
        city_total_pm += pm_value

    city_average = city_total_pm / len(city_pm_values)
    average_pm_by_city.append((city, city_average))
    print(f"  ค่าเฉลี่ย: {city_average:.2f}")

    if city_average > worst_city_avg:
        worst_city_avg = city_average
        worst_city_name = city

print("\nสรุปผล:")
print(f"- จังหวัดที่มีคุณภาพอากาศแย่ที่สุด: {worst_city_name} (ค่าเฉลี่ย {worst_city_avg:.2f})")


=== วิเคราะห์คุณภาพอากาศ 3 จังหวัด ===

กรุงเทพ:
  วันที่ 1: PM2.5 = 45 🟢 ดี
  วันที่ 2: PM2.5 = 50 🟢 ดี
  วันที่ 3: PM2.5 = 55 🟡 ปานกลาง
  วันที่ 4: PM2.5 = 48 🟢 ดี
  วันที่ 5: PM2.5 = 52 🟡 ปานกลาง
  วันที่ 6: PM2.5 = 60 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 58 🟡 ปานกลาง
  ค่าเฉลี่ย: 52.57

เชียงใหม่:
  วันที่ 1: PM2.5 = 85 🟡 ปานกลาง
  วันที่ 2: PM2.5 = 90 🟡 ปานกลาง
  วันที่ 3: PM2.5 = 120 🟠 แย่
  วันที่ 4: PM2.5 = 95 🟡 ปานกลาง
  วันที่ 5: PM2.5 = 100 🟡 ปานกลาง
  วันที่ 6: PM2.5 = 88 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 92 🟡 ปานกลาง
  ค่าเฉลี่ย: 95.71

ขอนแก่น:
  วันที่ 1: PM2.5 = 55 🟡 ปานกลาง
  วันที่ 2: PM2.5 = 60 🟡 ปานกลาง
  วันที่ 3: PM2.5 = 65 🟡 ปานกลาง
  วันที่ 4: PM2.5 = 58 🟡 ปานกลาง
  วันที่ 5: PM2.5 = 62 🟡 ปานกลาง
  วันที่ 6: PM2.5 = 70 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 68 🟡 ปานกลาง
  ค่าเฉลี่ย: 62.57

สรุปผล:
- จังหวัดที่มีคุณภาพอากาศแย่ที่สุด: เชียงใหม่ (ค่าเฉลี่ย 95.71)


---
# ส่วนที่ 6: 🎯 Mini Project - ระบบวิเคราะห์คุณภาพอากาศ

## โจทย์โปรเจกต์

สร้างโปรแกรมวิเคราะห์คุณภาพอากาศที่สามารถ:

### ข้อมูลที่ให้:
- 5 จังหวัด: กรุงเทพ, เชียงใหม่, ขอนแก่น, ภูเก็ต, อุดรธานี
- ข้อมูล PM2.5 รายวัน 7 วัน

### โปรแกรมต้องทำได้:
1. **แสดงข้อมูล PM2.5** ทุกจังหวัดทุกวัน พร้อมจำแนกระดับคุณภาพอากาศ
2. **คำนวณค่าเฉลี่ย PM2.5** ของแต่ละจังหวัด
3. **หาจังหวัดที่มีคุณภาพอากาศแย่ที่สุด** (ค่าเฉลี่ยสูงสุด)
4. **นับจำนวนวันที่อากาศดี** (PM2.5 < 50) ทั้งหมด
5. **สรุปรายงาน** ในรูปแบบที่อ่านง่าย

### เกณฑ์จำแนกคุณภาพอากาศ:
- PM2.5 ≤ 50: ดี 🟢
- 51-100: ปานกลาง 🟡
- 101-150: แย่ 🟠
- > 150: อันตราย 🔴

In [ ]:
# ข้อมูลสำหรับโปรเจกต์
provinces = ['กรุงเทพ', 'เชียงใหม่', 'ขอนแก่น', 'ภูเก็ต', 'อุดรธานี']

pm25_data = [
    [45, 52, 48, 55, 50, 58, 53],    # กรุงเทพ
    [95, 110, 125, 105, 115, 98, 102], # เชียงใหม่
    [62, 68, 70, 65, 72, 69, 71],    # ขอนแก่น
    [38, 42, 40, 45, 43, 48, 41],    # ภูเก็ต
    [78, 85, 82, 88, 80, 92, 86]     # อุดรธานี
]

print("✅ ข้อมูลพร้อมแล้ว! เริ่มเขียนโค้ดได้เลย")
def classify_pm25(pm_value):
    if pm_value <= 50:
        return f"{pm_value} 🟢 ดี"
    elif 51 <= pm_value <= 100:
        return f"{pm_value} 🟡 ปานกลาง"
    elif 101 <= pm_value <= 150:
        return f"{pm_value} 🟠 แย่"
    else:
        return f"{pm_value} 🔴 อันตราย!"

print("=== วิเคราะห์คุณภาพอากาศ 5 จังหวัด ===")

average_pm_by_province = []
worst_province_avg = -1
worst_province_name = ""

for i, province in enumerate(provinces):
    print(f"\n{province}:")
    province_pm_values = pm25_data[i]
    province_total_pm = 0

    for day_idx, pm_value in enumerate(province_pm_values):
        classification = classify_pm25(pm_value)
        print(f"  วันที่ {day_idx+1}: PM2.5 = {classification}")
        province_total_pm += pm_value
        if pm_value < 50:
            good_air_days_in_province += 1

    province_average = province_total_pm / len(province_pm_values)
    average_pm_by_province.append((province, province_average))
    print(f"  ค่าเฉลี่ย: {province_average:.2f}")

    if province_average > worst_province_avg:
        worst_province_avg = province_average
        worst_province_name = province

    good_air_days_total += good_air_days_in_province

print("\nสรุปผล:")
print(f"- จังหวัดที่มีคุณภาพอากาศแย่ที่สุด: {worst_province_name} (ค่าเฉลี่ย {worst_province_avg:.2f})")
print(f"- จำนวนวันที่อากาศดีทั้งหมด: {good_air_days_total} วัน")

✅ ข้อมูลพร้อมแล้ว! เริ่มเขียนโค้ดได้เลย
=== วิเคราะห์คุณภาพอากาศ 5 จังหวัด ===

กรุงเทพ:
  วันที่ 1: PM2.5 = 45 🟢 ดี
  วันที่ 2: PM2.5 = 52 🟡 ปานกลาง
  วันที่ 3: PM2.5 = 48 🟢 ดี
  วันที่ 4: PM2.5 = 55 🟡 ปานกลาง
  วันที่ 5: PM2.5 = 50 🟢 ดี
  วันที่ 6: PM2.5 = 58 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 53 🟡 ปานกลาง
  ค่าเฉลี่ย: 51.57

เชียงใหม่:
  วันที่ 1: PM2.5 = 95 🟡 ปานกลาง
  วันที่ 2: PM2.5 = 110 🟠 แย่
  วันที่ 3: PM2.5 = 125 🟠 แย่
  วันที่ 4: PM2.5 = 105 🟠 แย่
  วันที่ 5: PM2.5 = 115 🟠 แย่
  วันที่ 6: PM2.5 = 98 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 102 🟠 แย่
  ค่าเฉลี่ย: 107.14

ขอนแก่น:
  วันที่ 1: PM2.5 = 62 🟡 ปานกลาง
  วันที่ 2: PM2.5 = 68 🟡 ปานกลาง
  วันที่ 3: PM2.5 = 70 🟡 ปานกลาง
  วันที่ 4: PM2.5 = 65 🟡 ปานกลาง
  วันที่ 5: PM2.5 = 72 🟡 ปานกลาง
  วันที่ 6: PM2.5 = 69 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 71 🟡 ปานกลาง
  ค่าเฉลี่ย: 68.14

ภูเก็ต:
  วันที่ 1: PM2.5 = 38 🟢 ดี
  วันที่ 2: PM2.5 = 42 🟢 ดี
  วันที่ 3: PM2.5 = 40 🟢 ดี
  วันที่ 4: PM2.5 = 45 🟢 ดี
  วันที่ 5: PM2.5 = 43 🟢 ดี
  วันที่ 6: PM2.5 =

## 💡 คำแนะนำ (Hints)

1. ใช้ **nested loop** วนผ่านทุกจังหวัดและทุกวัน
2. ใช้ **if-elif-else** จำแนกระดับคุณภาพอากาศ
3. สร้าง **list** เก็บค่าเฉลี่ยของแต่ละจังหวัด
4. ใช้ตัวแปรนับจำนวนวันที่อากาศดี
5. ค่อยๆ ทำทีละส่วน ทดสอบไปเรื่อยๆ

## ตัวอย่าง Output ที่ต้องการ:

```
=== วิเคราะห์คุณภาพอากาศ 5 จังหวัด ===

กรุงเทพ:
  วันที่ 1: PM2.5 = 45 🟢 ดี
  วันที่ 2: PM2.5 = 52 🟡 ปานกลาง
  ...
  ค่าเฉลี่ย: 51.57

เชียงใหม่:
  วันที่ 1: PM2.5 = 95 🟡 ปานกลาง
  ...

สรุปผล:
- จังหวัดที่มีคุณภาพอากาศแย่ที่สุด: เชียงใหม่ (ค่าเฉลี่ย 107.14)
- จำนวนวันที่อากาศดี: 8 วัน
```

In [ ]:
# 🎯 Mini Project: เขียนโค้ดของคุณที่นี่

print("=" * 50)
print("=== วิเคราะห์คุณภาพอากาศ 5 จังหวัด ===")
print("=" * 50)

# เขียนโค้ดตรงนี้
provinces = ['กรุงเทพ' , 'เชียงใหม่' , 'ขอนแก่น' , 'ภูเก็ต' , 'อุดรธานี']
pm25_data = [
    [45, 52, 48, 55, 50, 58, 53],    # กรุงเทพ
    [95, 110, 125, 105, 115, 98, 102], # เชียงใหม่
    [62, 68, 70, 65, 72, 69, 71],    # ขอนแก่น
    [38, 42, 40, 45, 43, 48, 41],    # ภูเก็ต
    [78, 85, 82, 88, 80, 92, 86]     # อุดรธานี
]

# จำแนกระดับคุณภาพอากาศ
def classify_pm25(pm_value):
    if pm_value <= 50:
        return f"{pm_value} 🟢 ดี"
    elif 51 <= pm_value <= 100:
        return f"{pm_value} 🟡 ปานกลาง"
    elif 101 <= pm_value <= 150:
        return f"{pm_value} 🟠 แย่"
    else:
        return f"{pm_value} 🔴 อันตราย!"

# เก็บค่าเฉลี่ยของแต่ละจังหวัด
average_pm_by_province = []
worst_province_avg = -1
worst_province_name = ""
good_air_days_total = 0

# วนลูปแต่ละจังหวัด
for i, province in enumerate(provinces):
  print(f"\n{province}:")
  province_pm_values = pm25_data[i]
  province_total_pm = 0
  good_air_days_in_province = 0

  # วนลูปผ่านข้อมูล PM2.5 แต่ละวันของจังหวัด
  for day_idx, pm_value in enumerate(province_pm_values):
    classification = classify_pm25(pm_value)
    print(f"  วันที่ {day_idx+1}: PM2.5 = {classification}")
    province_total_pm += pm_value
    if pm_value < 50:
      good_air_days_in_province += 1

  # คำนวณค่าเฉลี่ย PM2.5 ของจังหวัด
  province_average = province_total_pm / len(province_pm_values)
  average_pm_by_province.append((province, province_average))
  print(f"  ค่าเฉลี่ย: {province_average:.2f}")

  if province_average > worst_province_avg:
    worst_province_avg = province_average
    worst_province_name = province

  # นับจำนวนวันที่อากาศดี
  good_air_days_total += good_air_days_in_province

print("\n" + "=" * 50)
print("สรุปผลการวิเคราะห์:")
print("=" * 50)
print(f"จังหวัดที่มีคุณภาพอากาศแย่ที่สุด : {worst_province_name} (ค่าเฉลี่ย {worst_province_avg:.2f})")
print(f"จำนวนวันที่อากาศดีทั้งหมด: {good_air_days_total} วัน")

print("\n" + "=" * 50)
print("จบการวิเคราะห์")
print("=" * 50)

=== วิเคราะห์คุณภาพอากาศ 5 จังหวัด ===

กรุงเทพ:
  วันที่ 1: PM2.5 = 45 🟢 ดี
  วันที่ 2: PM2.5 = 52 🟡 ปานกลาง
  วันที่ 3: PM2.5 = 48 🟢 ดี
  วันที่ 4: PM2.5 = 55 🟡 ปานกลาง
  วันที่ 5: PM2.5 = 50 🟢 ดี
  วันที่ 6: PM2.5 = 58 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 53 🟡 ปานกลาง
  ค่าเฉลี่ย: 51.57

เชียงใหม่:
  วันที่ 1: PM2.5 = 95 🟡 ปานกลาง
  วันที่ 2: PM2.5 = 110 🟠 แย่
  วันที่ 3: PM2.5 = 125 🟠 แย่
  วันที่ 4: PM2.5 = 105 🟠 แย่
  วันที่ 5: PM2.5 = 115 🟠 แย่
  วันที่ 6: PM2.5 = 98 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 102 🟠 แย่
  ค่าเฉลี่ย: 107.14

ขอนแก่น:
  วันที่ 1: PM2.5 = 62 🟡 ปานกลาง
  วันที่ 2: PM2.5 = 68 🟡 ปานกลาง
  วันที่ 3: PM2.5 = 70 🟡 ปานกลาง
  วันที่ 4: PM2.5 = 65 🟡 ปานกลาง
  วันที่ 5: PM2.5 = 72 🟡 ปานกลาง
  วันที่ 6: PM2.5 = 69 🟡 ปานกลาง
  วันที่ 7: PM2.5 = 71 🟡 ปานกลาง
  ค่าเฉลี่ย: 68.14

ภูเก็ต:
  วันที่ 1: PM2.5 = 38 🟢 ดี
  วันที่ 2: PM2.5 = 42 🟢 ดี
  วันที่ 3: PM2.5 = 40 🟢 ดี
  วันที่ 4: PM2.5 = 45 🟢 ดี
  วันที่ 5: PM2.5 = 43 🟢 ดี
  วันที่ 6: PM2.5 = 48 🟢 ดี
  วันที่ 7: PM2.5 = 41 🟢 ดี
  ค

---
# ส่วนที่ 7: 📚 สรุปและ Take-home Messages

## สรุปโครงสร้างการควบคุมทั้งหมด

### 1. คำสั่งเงื่อนไข
```python
if เงื่อนไข:
    # ทำถ้าเป็นจริง
elif เงื่อนไขอื่น:
    # ทำถ้าเงื่อนไขอื่นเป็นจริง
else:
    # ทำถ้าทุกเงื่อนไขเป็นเท็จ
```

### 2. for loop
```python
for item in list:
    # ทำซ้ำสำหรับทุก item

for i in range(10):
    # ทำซ้ำ 10 รอบ

for i, value in enumerate(list):
    # ได้ทั้ง index และ value
```

### 3. while loop
```python
while เงื่อนไข:
    # ทำซ้ำตราบใดที่เงื่อนไขเป็นจริง
```

### 4. การควบคุม loop
- **break**: หยุด loop ทันที
- **continue**: ข้ามรอบนี้ไปรอบถัดไป

### 5. Nested loops
```python
for row in data:
    for col in row:
        # ทำกับข้อมูลแบบตาราง
```

---

## 💡 เมื่อไหร่ใช้อะไร?

| สถานการณ์ | ใช้ |
|-----------|-----|
| ต้องการตัดสินใจ | if-elif-else |
| รู้จำนวนรอบที่แน่นอน | for loop |
| ไม่รู้จำนวนรอบ, ต้องการวนจนกว่าเงื่อนไขจะเป็นเท็จ | while loop |
| ต้องการหยุดก่อนครบ | break |
| ต้องการข้ามบางรอบ | continue |
| ข้อมูลแบบตาราง/grid | nested loops |

---

## ✅ Tips การเขียนโค้ดที่ดี

1. **เขียนให้อ่านง่าย** - ใช้ชื่อตัวแปรที่สื่อความหมาย
2. **เยื้อง (indent) ให้ถูกต้อง** - Python บังคับให้ indent
3. **เริ่มจากง่ายไปยาก** - แก้ปัญหาทีละส่วน
4. **ทดสอบบ่อยๆ** - รันโค้ดทุกครั้งที่เพิ่มอะไรใหม่
5. **ใส่ comment** - อธิบายส่วนที่ซับซ้อน

---

## 📖 แนะนำแหล่งเรียนรู้เพิ่มเติม

- [Python Official Tutorial](https://docs.python.org/3/tutorial/)
- [Real Python - Control Flow](https://realpython.com/python-conditional-statements/)
- [W3Schools Python](https://www.w3schools.com/python/)

---

## 🎓 ขั้นตอนต่อไป

หลังจากนี้ควรเรียนรู้:
1. **Functions** - สร้างฟังก์ชันของตัวเอง
2. **Lists และ Dictionaries** - โครงสร้างข้อมูลขั้นสูง
3. **File I/O** - อ่าน/เขียนไฟล์
4. **Libraries** - NumPy, Pandas สำหรับข้อมูลภูมิศาสตร์

---

# 🎉 สำเร็จ!

ยินดีด้วย! คุณได้เรียนรู้โครงสร้างการควบคุมใน Python แล้ว

**จงฝึกฝนต่อไป การเขียนโค้ดต้องอาศัยการฝึกซ้ำๆ** 💪

---

## 📝 บันทึกเพิ่มเติม

ใช้ cell นี้สำหรับบันทึกหรือทดลองโค้ดของคุณเอง

In [ ]:
# พื้นที่ทดลองของคุณ
# วิเคราะห์ข้อมูล grid 9x9 (เหมือน raster)

import random

# สร้างข้อมูล grid 9x9 แบบสุ่มสำหรับ PM2.5
# ค่าระหว่าง 30 ถึง 180 เพื่อให้มีคุณภาพอากาศที่หลากหลาย
grid_9x9 = [[random.randint(30, 180) for _ in range(9)] for _ in range(9)]

print("PM2.5 Grid (9x9):")
max_value_9x9 = 0
max_row_9x9 = 0
max_col_9x9 = 0

for row in range(len(grid_9x9)):
    for col in range(len(grid_9x9[row])):
        value = grid_9x9[row][col]
        print(f"  [{row},{col}] = {value}", end="  ")

        # หาค่าสูงสุด
        if value > max_value_9x9:
            max_value_9x9 = value
            max_row_9x9 = row
            max_col_9x9 = col
    print()  # ขึ้นบรรทัดใหม่เมื่อจบลูปคอลัมน์

print(f"\nค่าสูงสุดใน Grid 9x9: {max_value_9x9} ที่ตำแหน่ง [{max_row_9x9},{max_col_9x9}]")

PM2.5 Grid (9x9):
  [0,0] = 127    [0,1] = 115    [0,2] = 160    [0,3] = 134    [0,4] = 152    [0,5] = 109    [0,6] = 52    [0,7] = 167    [0,8] = 37  
  [1,0] = 165    [1,1] = 174    [1,2] = 147    [1,3] = 150    [1,4] = 133    [1,5] = 85    [1,6] = 174    [1,7] = 111    [1,8] = 101  
  [2,0] = 105    [2,1] = 113    [2,2] = 90    [2,3] = 125    [2,4] = 153    [2,5] = 172    [2,6] = 66    [2,7] = 155    [2,8] = 113  
  [3,0] = 121    [3,1] = 162    [3,2] = 45    [3,3] = 40    [3,4] = 109    [3,5] = 176    [3,6] = 175    [3,7] = 52    [3,8] = 174  
  [4,0] = 135    [4,1] = 128    [4,2] = 45    [4,3] = 35    [4,4] = 161    [4,5] = 169    [4,6] = 116    [4,7] = 73    [4,8] = 74  
  [5,0] = 145    [5,1] = 51    [5,2] = 33    [5,3] = 88    [5,4] = 92    [5,5] = 156    [5,6] = 48    [5,7] = 135    [5,8] = 162  
  [6,0] = 61    [6,1] = 55    [6,2] = 177    [6,3] = 90    [6,4] = 168    [6,5] = 162    [6,6] = 74    [6,7] = 111    [6,8] = 167  
  [7,0] = 64    [7,1] = 117    [7,2] = 136    [7,3]